C:\코드★\프로젝트\01\bingo\main.o	main.c:(.text+0x24): undefined reference to `init'
C:\코드★\프로젝트\01\bingo\main.o	main.c:(.text+0x30): undefined reference to `init'
C:\프로그래밍\Dev-Cpp\MinGW64\x86_64-w64-mingw32\lib\libmingw32.a(lib64_libmingw32_a-crt0_c.o)	In function `main':
18		C:\crossdev\src\mingw-w64-v3-git\mingw-w64-crt\crt\crt0_c.c	undefined reference to `WinMain'
C:\코드★\프로젝트\01\bingo\collect2.exe	[Error] ld returned 1 exit status
25		C:\코드★\프로젝트\01\bingo\Makefile.win	recipe for target 'Project1.exe' failed
